### ISSUE TITLE
Different options and misunderstands

### ISSUE THREAD

**Issue by Commekoma** [bananasov/LethalVibrations#1]
Hello ! Love your mod, do you know if there is a way to deeply personnalize the options ? Like if i want every naughty boy options but why good boy onces ? 
, can you explain me how multiplier works ? Is 100=100% of the dildo power ? Thank you for your help !

**Comment by bananasov** [comment]
the multiplier is just additive on top of the default value, configs can be found in `BepInEx/config` under the name `LethalVibrations`
